title: Қарақат жобасы
description: Қазақща Видео-Хостинг
theme: just-the-docs

url: https://biscript.github.io/caracat-paage

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
